#!/bin/sh

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
#export PATH=/opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin/:$PATH

make gxbb_p200_2G.dtb gxbb_p200.dtb gxbb_p201.dtb gxl_p212_1g.dtb gxl_p212_2g.dtb
