# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_100M.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_100M_RealtekWiFi.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_1Gbit.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_1Gbit_RealtekWiFi.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_mxq_pro_4k.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_1G_wetek_hub.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_100M.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_100M_RealtekWiFi.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_1Gbit.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_1Gbit_OTG_Port.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_1Gbit_RealtekWiFi.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_m8s+_k3_pro.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_minix_neo_u1.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_2G_wetek_play_2.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_k1_plus.dtb
dtb-$(CONFIG_ARM64) += gxbb_p200_k2_pro.dtb
dtb-$(CONFIG_ARM64) += gxbb_p201_2G.dtb
dtb-$(CONFIG_ARM64) += gxbb_p201.dtb
dtb-$(CONFIG_ARM64) += gxbb_skt.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g_AB.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g_coowell_v5.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g_lepotato.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g_nand.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_1g_slowemmc.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g_AB.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g_kvim.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g_lepotato.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g_nand.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_2g_slowemmc.dtb
dtb-$(CONFIG_ARM64) += gxl_p212_3g.dtb
dtb-$(CONFIG_ARM64) += gxl_p230_2g.dtb
dtb-$(CONFIG_ARM64) += gxl_p230_k1_pro.dtb
dtb-$(CONFIG_ARM64) += gxl_p231_1g.dtb
dtb-$(CONFIG_ARM64) += gxl_p231_1g_dvb.dtb
dtb-$(CONFIG_ARM64) += gxl_p231_2g.dtb
dtb-$(CONFIG_ARM64) += gxl_p231_2g_dvb.dtb
dtb-$(CONFIG_ARM64) += gxl_pxp.dtb
dtb-$(CONFIG_ARM64) += gxl_skt.dtb
dtb-$(CONFIG_ARM64) += gxm_kvim2.dtb
dtb-$(CONFIG_ARM64) += gxm_q200_1g.dtb
dtb-$(CONFIG_ARM64) += gxm_q200_2g.dtb
dtb-$(CONFIG_ARM64) += gxm_q200_2g_minix_neo_u9.dtb
dtb-$(CONFIG_ARM64) += gxm_q200_3g.dtb
dtb-$(CONFIG_ARM64) += gxm_q200_k3_pro.dtb
dtb-$(CONFIG_ARM64) += gxm_q201_1g.dtb
dtb-$(CONFIG_ARM64) += gxm_q201_2g.dtb
dtb-$(CONFIG_ARM64) += gxm_q201_3g.dtb
dtb-$(CONFIG_ARM64) += gxm_skt.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_9023_skt.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_p300.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_p301.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_p310.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_p311.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_pxp.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_skt.dtb
dtb-$(CONFIG_ARM64) += gxtvbb_t966_skt.dtb
dtb-$(CONFIG_ARM64) += kvim2_android.dtb
dtb-$(CONFIG_ARM64) += kvim2_linux.dtb
dtb-$(CONFIG_ARM64) += kvim2_multios.dtb
dtb-$(CONFIG_ARM64) += kvim_android.dtb
dtb-$(CONFIG_ARM64) += kvim.dtb
dtb-$(CONFIG_ARM64) += kvim_linux.dtb
dtb-$(CONFIG_ARM64) += kvim_multios.dtb
dtb-$(CONFIG_ARM64) += odroidc2.dtb
dtb-$(CONFIG_ARM64) += txl_p320.dtb
dtb-$(CONFIG_ARM64) += txl_p321_512m.dtb
dtb-$(CONFIG_ARM64) += txl_p321.dtb
dtb-$(CONFIG_ARM64) += txl_p321_v2.dtb
dtb-$(CONFIG_ARM64) += txl_p341.dtb
dtb-$(CONFIG_ARM64) += txl_pxp.dtb
dtb-$(CONFIG_ARM64) += txl_skt.dtb
dtb-$(CONFIG_ARM64) += txl_t950_skt.dtb
dtb-$(CONFIG_ARM64) += txl_t960_p346.dtb
dtb-$(CONFIG_ARM64) += txl_t960_skt.dtb

targets += dtbs

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif
targets += $(DTB_LIST)

dtbs: $(addprefix $(obj)/, $(DTB_LIST))

clean-files := dts/*.dtb *.dtb
